# Generated by Django 6.0.2 on 2026-03-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Human-readable title, e.g. 'Hard Midterm Question 2'.", max_length=200)),
                ('module_type', models.CharField(choices=[('CPU', 'CPU Scheduling'), ('MEMORY', 'Memory Management'), ('DISK', 'Disk Scheduling')], help_text='OS module category for this scenario.', max_length=10)),
                ('algorithm_used', models.CharField(help_text="Algorithm name, e.g. 'FCFS', 'SJF', 'LRU'.", max_length=100)),
                ('input_data', models.JSONField(help_text='Flexible JSON payload storing process definitions, burst times, memory requests, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_slug', models.SlugField(editable=False, help_text='Auto-generated short slug for sharing.', max_length=12, unique=True)),
            ],
            options={
                'verbose_name': 'Simulation Scenario',
                'verbose_name_plural': 'Simulation Scenarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
