"""
DRF serializers for the simulations app.

Handles validation and JSON ↔ model conversion for the
SimulationScenario model.
"""

from rest_framework import serializers

from .models import SimulationScenario


class SimulationScenarioSerializer(serializers.ModelSerializer):
    """
    Serializer for SimulationScenario.

    - On CREATE (POST): ``share_slug`` and ``created_at`` are read-only
      and auto-generated by the model.
    - On READ (GET): all fields are returned.
    """

    class Meta:
        model = SimulationScenario
        fields = [
            "id",
            "title",
            "module_type",
            "algorithm_used",
            "input_data",
            "created_at",
            "share_slug",
        ]
        read_only_fields = ["id", "created_at", "share_slug"]
